### ISSUE TITLE
inspector db viewer stops working when using workspaces

### ISSUE THREAD

**Issue by timeyyy** [fulcrologic/fulcro-inspect#68] opened 2019-09-20 13:43 UTC
Fulcroinspect version 1.0.16.
Chrome Version 76.0.3809.132 (Official Build) (64-bit)
Os: Mac 10.14.6 (18G95)

I have one workspaces defcard  that will stop the fulcro inspect db viewer from working. (clicking on the `inspector` button for the card does nothing)  After attempting to open this card i need to restart chrome for the inspector to work.

The card renders and works fine. The name of the card is `playlist-viewer-factory`. If i change the name of the card to be something else (then restart chrome) the inspector works. 

Not really sure what other information would be helpful in debugging this, feel free to ask.

**Comment by awkay** [comment] 2019-09-20 14:47
So the way the database viewer works: it sends diffs of the database from the client to the chrome extension (for speed).  I've seen it as well (the db viewer loses track of state). Perhaps you have an example that triggers it more reliably. I doubt the name has anything to do with it. Perhaps you've got non-serializable state in your app state that is confusing it. We try to send over a placeholder for those things (security makes it impossible to send the actual values to a chrome extension).

**Comment by awkay** [comment] 2019-09-20 14:52
Duplicate of #56

**Closed by awkay** 2019-09-20 14:52 UTC
